#place = ['tokyo' , 'hong kong' , 'alaska' , 'zermatt' , 'taiwan']
#print(place)
#print(sorted(place))
#print(place)
#place.reverse()
#print(place)
#place.reverse()
#print(place)
#place.sort()
#print(place)
#place.sort(reverse=True)
#print(place)

list = ['nintendo64' , 'playstaiton' , 'xbox' , 'pc' , 'gamboy']
#print(list)
#print(sorted(list))
#print(list)
#print(sorted(list, reverse = True))
#print(list)
print(list)
list.sort()
print(list)
list.reverse()
print(list)
